set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARMv7-M)

set(PLATFORM_VARIANT ${PLATFORM}${FLASH_SIZE})
message(STATUS "PLATFORM_VARIANT: ${PLATFORM_VARIANT}")

set(TOOLCHAIN_PREFIX arm-none-eabi-)
find_program(BINUTILS_PATH ${TOOLCHAIN_PREFIX}gcc NO_CACHE)

if (NOT BINUTILS_PATH)
    message(FATAL_ERROR "ARM GCC toolchain not found")
endif ()

get_filename_component(ARM_TOOLCHAIN_DIR ${BINUTILS_PATH} DIRECTORY)
# Without that flag CMake is not able to pass test compilation check
if (${CMAKE_VERSION} VERSION_EQUAL "3.6.0" OR ${CMAKE_VERSION} VERSION_GREATER "3.6")
    message(STATUS "CMAKE_TRY_COMPILE_TARGET_TYPE: STATIC_LIBRARY")
	  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
else ()
   
endif ()

if (DEFINED LINKER_SCRIPT_PATH AND EXISTS ${LINKER_SCRIPT_PATH})
    set(LINKER_SCRIPT_PATH_LOCAL "${LINKER_SCRIPT_PATH}")
else()
    set(LINKER_SCRIPT_PATH_LOCAL "${TRIDENT_PLATFORM_PATH}/Library/RT58x/Device/GCC/app_gcc_cm3_mcu_2mb.ld")
endif()

message(STATUS "Linker Script Path: ${LINKER_SCRIPT_PATH_LOCAL}")

#TODO: what is the purpose of this? - Arch 09/03/2024
#math(EXPR NVM_STORAGE_SIZE "1024 * 32" OUTPUT_FORMAT HEXADECIMAL)

# TODO: review linker flags - Arch 09/03/2024
#set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nano.specs -T '${LINKER_SCRIPT_PATH_LOCAL}' -Xlinker --gc-sections -Xlinker --defsym -Xlinker NVM_STORAGE_SIZE=${NVM_STORAGE_SIZE}")
#set(CMAKE_EXE_LINKER_FLAGS_INIT "-lm -T '${LINKER_SCRIPT_PATH_LOCAL}' -Xlinker --gc-sections -Xlinker --defsym -Xlinker NVM_STORAGE_SIZE=${NVM_STORAGE_SIZE}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-T '${LINKER_SCRIPT_PATH_LOCAL}' -Wl,--print-memory-usage -Wl,--gc-sections -Wl,-Map=./${PROJECT_NAME}.map")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS_INIT}" CACHE STRING "" FORCE)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_AR ${TOOLCHAIN_PREFIX}gcc-ar)
set(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}gcc-ranlib)

execute_process(COMMAND ${CMAKE_C_COMPILER} -print-sysroot
    OUTPUT_VARIABLE ARM_GCC_SYSROOT OUTPUT_STRIP_TRAILING_WHITESPACE)

# Default ASM assembler flags
set(CMAKE_ASM_FLAGS_DEBUG "-g -Og -mthumb -mcpu=cortex-m3 -ffunction-sections -fdata-sections -DUSE_FREERTOS")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS_DEBUG_INIT}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_RELEASE_INIT "-Os -mthumb -mcpu=cortex-m3 -ffunction-sections -fdata-sections -DUSE_FREERTOS")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS_RELEASE_INIT}" CACHE STRING "" FORCE)

# Default C compiler flags
set(CMAKE_C_FLAGS_DEBUG_INIT "-g3 -Og -Wall -gdwarf-2 -mcpu=cortex-m3 -mthumb -std=c99 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=soft --specs=nosys.specs --specs=nano.specs")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE_INIT "-Os -Wall -mcpu=cortex-m3 -mthumb -std=c99 -ffunction-sections -fdata-sections -mfpu=fpv5-sp-d16 -mfloat-abi=soft --specs=nosys.specs --specs=nano.specs")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE_INIT}" CACHE STRING "" FORCE)

# Unused build configurations. Flags are not verified.
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-Os")
set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO_INIT}" CACHE STRING "" FORCE)

set(CMAKE_ASM_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO "${CMAKE_ASM_FLAGS_RELWITHDEBINFO_INIT}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_MINSIZEREL_INIT "-Os")
set(CMAKE_ASM_FLAGS_MINSIZEREL "${CMAKE_ASM_FLAGS_MINSIZEREL_INIT}" CACHE STRING "" FORCE)

# Default C++ compiler flags
# Unused.
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-g3 -Og")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Os")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT}" CACHE STRING "" FORCE)

set(CMAKE_OBJCOPY ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_SYSROOT ${ARM_GCC_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
